version: '3'

services:
  app:
    image: ghcr.io/aya-soghayyer/expense-tracker:$GIT_VERSION
    restart: always
    environment: 
       - DB_HOST=$DB_HOST
       - DB_USER=$DB_USER 
       - DB_PASSWORD=$DB_PASSWORD
       - DB_NAME=$DB_NAME
       - DB_PORT=$DB_PORT
       - currency_key_access=$currency_key_access
       - PORT=$PORT
    ports:
      - "80:80"